
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'JonetV15_UE_AD9361.ucf'
####################################################################################


set_property PACKAGE_PIN D15 [get_ports FPGA_CLK]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:3
# The conversion of 'IOSTANDARD' constraint on 'net' object 'FPGA_CLK' has been applied to the port object 'FPGA_CLK'.
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_CLK]

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# In xdc, all clocks are related by default. This differs from ucf, where clocks are unrelated unless specified otherwise. As a result, you may now see cross-clock paths that were previously unconstrained in ucf. Commented out xdc false path constraints have been generated and can be uncommented, should you wish to remove these new paths. These commands are located after the last clock definition

# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:5
create_clock -period 40.000 -name FPGA_CLK [get_ports FPGA_CLK]

#NET "processing_system7_0_UART0_TX_pin"  IOSTANDARD = LVCMOS33 | LOC = Y17;
#NET "processing_system7_0_UART0_RX_pin"  IOSTANDARD = LVCMOS33 | LOC = Y16;
#NET "UART0_RX_Test_Out"						  IOSTANDARD = LVCMOS33 | LOC = AC19;

#set_property PACKAGE_PIN V19 [get_ports AFC_Out]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:12
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AFC_Out' has been applied to the port object 'AFC_Out'.
#set_property IOSTANDARD LVCMOS33 [get_ports AFC_Out]

#	AD9361-ctrl
set_property PACKAGE_PIN A15 [get_ports {RF_CTRL_IN[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:16
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RF_CTRL_IN[0]' has been applied to the port object 'RF_CTRL_IN[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[0]}]
#	AD9361-ctrl
set_property PACKAGE_PIN B15 [get_ports {RF_CTRL_IN[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:19
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RF_CTRL_IN[1]' has been applied to the port object 'RF_CTRL_IN[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[1]}]
#	AD9361-ctrl
set_property PACKAGE_PIN A14 [get_ports {RF_CTRL_IN[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:22
# The conversion of 'IOSTANDARD' constraint on 'net' object 'm54_CtrlSig_Analog_Debug[0]' has been applied to the port object 'RF_CTRL_IN[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[2]}]
#	AD9361-ctrl
set_property PACKAGE_PIN B14 [get_ports {RF_CTRL_IN[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:25
# The conversion of 'IOSTANDARD' constraint on 'net' object 'm54_CtrlSig_Analog_Debug[0]' has been applied to the port object 'RF_CTRL_IN[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {RF_CTRL_IN[3]}]

# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:27
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PA_EN' has been applied to the port object 'PA_EN'.
set_property IOSTANDARD LVCMOS33 [get_ports PA_EN]
set_property PACKAGE_PIN AE11 [get_ports PA_EN]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:29
# The conversion of 'IOSTANDARD' constraint on 'net' object 'RF_SW' has been applied to the port object 'RF_SW'.
set_property IOSTANDARD LVCMOS33 [get_ports RF_SW]
set_property PACKAGE_PIN AE10 [get_ports RF_SW]


set_property PACKAGE_PIN K2 [get_ports {TEST_LED[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:34
# The conversion of 'IOSTANDARD' constraint on 'net' object 'TEST_LED[0]' has been applied to the port object 'TEST_LED[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[0]}]
set_property PACKAGE_PIN K1 [get_ports {TEST_LED[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:36
# The conversion of 'IOSTANDARD' constraint on 'net' object 'TEST_LED[1]' has been applied to the port object 'TEST_LED[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[1]}]
set_property PACKAGE_PIN H2 [get_ports {TEST_LED[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:38
# The conversion of 'IOSTANDARD' constraint on 'net' object 'TEST_LED[2]' has been applied to the port object 'TEST_LED[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[2]}]
set_property PACKAGE_PIN G1 [get_ports {TEST_LED[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:40
# The conversion of 'IOSTANDARD' constraint on 'net' object 'TEST_LED[3]' has been applied to the port object 'TEST_LED[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_LED[3]}]

#D27
set_property PACKAGE_PIN F10 [get_ports SPI_CLK]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:44
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SPI_CLK' has been applied to the port object 'SPI_CLK'.
set_property IOSTANDARD LVCMOS18 [get_ports SPI_CLK]
#D26
set_property PACKAGE_PIN B6 [get_ports SPI_ENB]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:47
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SPI_ENB' has been applied to the port object 'SPI_ENB'.
set_property IOSTANDARD LVCMOS18 [get_ports SPI_ENB]
#C26
set_property PACKAGE_PIN H7 [get_ports SPI_DI]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:50
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SPI_DI' has been applied to the port object 'SPI_DI'.
set_property IOSTANDARD LVCMOS18 [get_ports SPI_DI]
#C27
set_property PACKAGE_PIN B12 [get_ports SPI_DO]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:53
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SPI_DO' has been applied to the port object 'SPI_DO'.
set_property IOSTANDARD LVCMOS18 [get_ports SPI_DO]

#H31
set_property PACKAGE_PIN C11 [get_ports AD9361_RST]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:57
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RST' has been applied to the port object 'AD9361_RST'.
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_RST]
#G18
set_property PACKAGE_PIN A5 [get_ports AD9361_EN]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:60
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_EN' has been applied to the port object 'AD9361_EN'.
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_EN]
#G19
set_property PACKAGE_PIN H6 [get_ports AD9361_Tx_Rx]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:63
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_Tx_Rx' has been applied to the port object 'AD9361_Tx_Rx'.
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_Tx_Rx]
#H22
set_property PACKAGE_PIN E10 [get_ports AD9361_EN_AGC]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:66
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_EN_AGC' has been applied to the port object 'AD9361_EN_AGC'.
set_property IOSTANDARD LVCMOS18 [get_ports AD9361_EN_AGC]

#D14
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:70
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_Frame_P' has been applied to the port object 'AD9361_TX_Frame_P'.
set_property IOSTANDARD LVDS [get_ports AD9361_TX_Frame_P]
#D15
set_property PACKAGE_PIN D5 [get_ports AD9361_TX_Frame_N]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:73
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_Frame_N' has been applied to the port object 'AD9361_TX_Frame_N'.
set_property IOSTANDARD LVDS [get_ports AD9361_TX_Frame_N]

#G12
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:77
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_FB_CLK_P' has been applied to the port object 'AD9361_FB_CLK_P'.
set_property IOSTANDARD LVDS [get_ports AD9361_FB_CLK_P]
#G13
set_property PACKAGE_PIN G5 [get_ports AD9361_FB_CLK_N]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:80
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_FB_CLK_N' has been applied to the port object 'AD9361_FB_CLK_N'.
set_property IOSTANDARD LVDS [get_ports AD9361_FB_CLK_N]


#H16
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:85
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_P[0]' has been applied to the port object 'AD9361_TX_DATA_P[0]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[0]}]
#H17
set_property PACKAGE_PIN D8 [get_ports {AD9361_TX_DATA_N[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:88
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_N[0]' has been applied to the port object 'AD9361_TX_DATA_N[0]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[0]}]

#G15
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:92
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_P[1]' has been applied to the port object 'AD9361_TX_DATA_P[1]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[1]}]
#G16
set_property PACKAGE_PIN E8 [get_ports {AD9361_TX_DATA_N[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:95
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_N[1]' has been applied to the port object 'AD9361_TX_DATA_N[1]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[1]}]

#D17
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:99
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_P[2]' has been applied to the port object 'AD9361_TX_DATA_P[2]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[2]}]
#D18
set_property PACKAGE_PIN A7 [get_ports {AD9361_TX_DATA_N[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_N[2]' has been applied to the port object 'AD9361_TX_DATA_N[2]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[2]}]

#C14
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:106
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_P[3]' has been applied to the port object 'AD9361_TX_DATA_P[3]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[3]}]
#C15
set_property PACKAGE_PIN A8 [get_ports {AD9361_TX_DATA_N[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:109
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_N[3]' has been applied to the port object 'AD9361_TX_DATA_N[3]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[3]}]

#C18
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:113
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_P[4]' has been applied to the port object 'AD9361_TX_DATA_P[4]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[4]}]
#C19
set_property PACKAGE_PIN B9 [get_ports {AD9361_TX_DATA_N[4]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:116
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_N[4]' has been applied to the port object 'AD9361_TX_DATA_N[4]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[4]}]

#H19
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:120
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_P[5]' has been applied to the port object 'AD9361_TX_DATA_P[5]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_P[5]}]
#H20
set_property PACKAGE_PIN A10 [get_ports {AD9361_TX_DATA_N[5]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:123
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_TX_DATA_N[5]' has been applied to the port object 'AD9361_TX_DATA_N[5]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_TX_DATA_N[5]}]

#D8 01P
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:127
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_Frame_P' has been applied to the port object 'AD9361_RX_Frame_P'.
set_property IOSTANDARD LVDS [get_ports AD9361_RX_Frame_P]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:128
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_Frame_P' has been applied to the port object 'AD9361_RX_Frame_P'.
set_property DIFF_TERM TRUE [get_ports AD9361_RX_Frame_P]
#D9	01N
set_property PACKAGE_PIN C6 [get_ports AD9361_RX_Frame_N]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:131
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_Frame_N' has been applied to the port object 'AD9361_RX_Frame_N'.
set_property IOSTANDARD LVDS [get_ports AD9361_RX_Frame_N]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:132
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_Frame_N' has been applied to the port object 'AD9361_RX_Frame_N'.
set_property DIFF_TERM TRUE [get_ports AD9361_RX_Frame_N]

#G6 00P
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:136
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_DATA_CLK_P' has been applied to the port object 'AD9361_DATA_CLK_P'.
set_property IOSTANDARD LVDS [get_ports AD9361_DATA_CLK_P]
#G7 00N
set_property PACKAGE_PIN C7 [get_ports AD9361_DATA_CLK_N]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:139
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_DATA_CLK_N' has been applied to the port object 'AD9361_DATA_CLK_N'.
set_property IOSTANDARD LVDS [get_ports AD9361_DATA_CLK_N]

#H8 02N
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:143
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_N[0]' has been applied to the port object 'AD9361_RX_DATA_N[0]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:144
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_N[0]' has been applied to the port object 'AD9361_RX_DATA_N[0]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[0]}]
#H7 02P
set_property PACKAGE_PIN F5 [get_ports {AD9361_RX_DATA_P[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:147
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_P[0]' has been applied to the port object 'AD9361_RX_DATA_P[0]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:148
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_P[0]' has been applied to the port object 'AD9361_RX_DATA_P[0]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[0]}]
#G10 03N
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:151
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_N[1]' has been applied to the port object 'AD9361_RX_DATA_N[1]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:152
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_N[1]' has been applied to the port object 'AD9361_RX_DATA_N[1]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[1]}]
#G9 03P
set_property PACKAGE_PIN A4 [get_ports {AD9361_RX_DATA_P[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:155
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_P[1]' has been applied to the port object 'AD9361_RX_DATA_P[1]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:156
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_P[1]' has been applied to the port object 'AD9361_RX_DATA_P[1]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[1]}]
#H11 04N
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:159
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_N[2]' has been applied to the port object 'AD9361_RX_DATA_N[2]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:160
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_N[2]' has been applied to the port object 'AD9361_RX_DATA_N[2]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[2]}]
#H10 04P
set_property PACKAGE_PIN C4 [get_ports {AD9361_RX_DATA_P[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:163
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_P[2]' has been applied to the port object 'AD9361_RX_DATA_P[2]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:164
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_P[2]' has been applied to the port object 'AD9361_RX_DATA_P[2]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[2]}]
#D12 05N
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:167
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_N[3]' has been applied to the port object 'AD9361_RX_DATA_N[3]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:168
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_N[3]' has been applied to the port object 'AD9361_RX_DATA_N[3]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[3]}]
#D11 05P
set_property PACKAGE_PIN C2 [get_ports {AD9361_RX_DATA_P[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:171
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_P[3]' has been applied to the port object 'AD9361_RX_DATA_P[3]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:172
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_P[3]' has been applied to the port object 'AD9361_RX_DATA_P[3]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[3]}]
#C11 06N
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:175
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_N[4]' has been applied to the port object 'AD9361_RX_DATA_N[4]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[4]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:176
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_N[4]' has been applied to the port object 'AD9361_RX_DATA_N[4]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[4]}]
#C10 06P
set_property PACKAGE_PIN B2 [get_ports {AD9361_RX_DATA_P[4]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:179
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_P[4]' has been applied to the port object 'AD9361_RX_DATA_P[4]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[4]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:180
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_P[4]' has been applied to the port object 'AD9361_RX_DATA_P[4]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[4]}]
#H14 07N
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:183
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_N[5]' has been applied to the port object 'AD9361_RX_DATA_N[5]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_N[5]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:184
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_N[5]' has been applied to the port object 'AD9361_RX_DATA_N[5]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_N[5]}]
#H13 07P
set_property PACKAGE_PIN B5 [get_ports {AD9361_RX_DATA_P[5]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:187
# The conversion of 'IOSTANDARD' constraint on 'net' object 'AD9361_RX_DATA_P[5]' has been applied to the port object 'AD9361_RX_DATA_P[5]'.
set_property IOSTANDARD LVDS [get_ports {AD9361_RX_DATA_P[5]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:188
# The conversion of 'DIFF_TERM' constraint on 'net' object 'AD9361_RX_DATA_P[5]' has been applied to the port object 'AD9361_RX_DATA_P[5]'.
set_property DIFF_TERM TRUE [get_ports {AD9361_RX_DATA_P[5]}]
#Created by Constraints Editor (xc7z045-ffg900-2) - 2014/08/29
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:192
create_clock -period 6.667 -name AD9361_DATA_CLK_P [get_ports AD9361_DATA_CLK_P]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:193
create_clock -period 6.667 -name AD9361_DATA_CLK_N [get_ports AD9361_DATA_CLK_N]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:208
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -max 1.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -clock_fall -max -add_delay 1.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -min 0.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_P] -clock_fall -min -add_delay 0.250 [get_ports {AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_P}]
#set_false_path -rise_from [get_clocks AD9361_DATA_CLK_P] -through [get_ports {AD9361_RX_DATA_N[1] AD9361_RX_DATA_N[2] AD9361_RX_DATA_N[3] AD9361_RX_DATA_N[4] AD9361_RX_DATA_N[5] AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_N AD9361_RX_Frame_P AD9361_RX_DATA_N[0]}] -fall_to [get_clocks AD9361_DATA_CLK_P]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:209
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -max 1.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -clock_fall -max -add_delay 1.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -min 0.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]
set_input_delay -clock [get_clocks AD9361_DATA_CLK_N] -clock_fall -min -add_delay 0.250 [get_ports {AD9361_DATA_CLK_N[0] AD9361_DATA_CLK_N[1] AD9361_DATA_CLK_N[2] AD9361_DATA_CLK_N[3] AD9361_DATA_CLK_N[4] AD9361_DATA_CLK_N[5] AD9361_RX_Frame_N}]
#set_false_path -fall_from [get_clocks AD9361_DATA_CLK_P] -through [get_ports {AD9361_RX_DATA_N[1] AD9361_RX_DATA_N[2] AD9361_RX_DATA_N[3] AD9361_RX_DATA_N[4] AD9361_RX_DATA_N[5] AD9361_RX_DATA_P[0] AD9361_RX_DATA_P[1] AD9361_RX_DATA_P[2] AD9361_RX_DATA_P[3] AD9361_RX_DATA_P[4] AD9361_RX_DATA_P[5] AD9361_RX_Frame_N AD9361_RX_Frame_P AD9361_RX_DATA_N[0]}] -rise_to [get_clocks AD9361_DATA_CLK_P]

##	MII/TS	B12
#set_property PACKAGE_PIN AC14 [get_ports ST_CLK]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:213
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_CLK' has been applied to the port object 'ST_CLK'.
#set_property IOSTANDARD LVCMOS33 [get_ports ST_CLK]
##	MII/TS	B12
#set_property PACKAGE_PIN AD15 [get_ports ST_EN]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:216
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_EN' has been applied to the port object 'ST_EN'.
#set_property IOSTANDARD LVCMOS33 [get_ports ST_EN]
##	MII/TS	B12
#set_property PACKAGE_PIN AC13 [get_ports ST_PSSYNC]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:219
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_PSSYNC' has been applied to the port object 'ST_PSSYNC'.
#set_property IOSTANDARD LVCMOS33 [get_ports ST_PSSYNC]
##	MII/TS	B12
#set_property PACKAGE_PIN AA14 [get_ports {ST_DATA[0]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:222
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[0]' has been applied to the port object 'ST_DATA[0]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[0]}]
##	MII/TS	B12
#set_property PACKAGE_PIN Y15 [get_ports {ST_DATA[1]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:225
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[1]' has been applied to the port object 'ST_DATA[1]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[1]}]
##	MII/TS	B12
#set_property PACKAGE_PIN AB14 [get_ports {ST_DATA[2]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:228
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[2]' has been applied to the port object 'ST_DATA[2]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[2]}]
##	MII/TS	B12
#set_property PACKAGE_PIN AA15 [get_ports {ST_DATA[3]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:231
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[3]' has been applied to the port object 'ST_DATA[3]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[3]}]
##	MII/TS	B12
#set_property PACKAGE_PIN AC16 [get_ports {ST_DATA[4]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:234
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[4]' has been applied to the port object 'ST_DATA[4]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[4]}]
##	MII/TS	B12
#set_property PACKAGE_PIN AD16 [get_ports {ST_DATA[5]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:237
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[5]' has been applied to the port object 'ST_DATA[5]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[5]}]
##	MII/TS	B12
#set_property PACKAGE_PIN AB17 [get_ports {ST_DATA[6]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:240
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[6]' has been applied to the port object 'ST_DATA[6]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[6]}]
##	MII/TS	B12
#set_property PACKAGE_PIN AC17 [get_ports {ST_DATA[7]}]
## E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:243
## The conversion of 'IOSTANDARD' constraint on 'net' object 'ST_DATA[7]' has been applied to the port object 'ST_DATA[7]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {ST_DATA[7]}]


#---------------MII-----------------------------------------------------------------
set_property PACKAGE_PIN AD20 [get_ports MIIFPGA_RXC]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:248
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_RXC' has been applied to the port object 'MIIFPGA_RXC'.
set_property IOSTANDARD LVCMOS33 [get_ports MIIFPGA_RXC]
set_property PACKAGE_PIN W20 [get_ports {MIIFPGA_RXD[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:250
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_RXD[0]' has been applied to the port object 'MIIFPGA_RXD[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_RXD[0]}]
set_property PACKAGE_PIN Y20 [get_ports {MIIFPGA_RXD[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:252
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_RXD[1]' has been applied to the port object 'MIIFPGA_RXD[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_RXD[1]}]
set_property PACKAGE_PIN AA25 [get_ports {MIIFPGA_RXD[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:254
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_RXD[2]' has been applied to the port object 'MIIFPGA_RXD[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_RXD[2]}]
set_property PACKAGE_PIN AA23 [get_ports {MIIFPGA_RXD[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:256
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_RXD[3]' has been applied to the port object 'MIIFPGA_RXD[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_RXD[3]}]
set_property PACKAGE_PIN AB25 [get_ports MIIFPGA_RXDV]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:258
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_RXDV' has been applied to the port object 'MIIFPGA_RXDV'.
set_property IOSTANDARD LVCMOS33 [get_ports MIIFPGA_RXDV]

set_property PACKAGE_PIN AD23 [get_ports MIIFPGA_TXC]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:261
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_TXC' has been applied to the port object 'MIIFPGA_TXC'.
set_property IOSTANDARD LVCMOS33 [get_ports MIIFPGA_TXC]
set_property PACKAGE_PIN AF23 [get_ports {MIIFPGA_TXD[0]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:263
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_TXD[0]' has been applied to the port object 'MIIFPGA_TXD[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_TXD[0]}]
set_property PACKAGE_PIN AE23 [get_ports {MIIFPGA_TXD[1]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:265
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_TXD[1]' has been applied to the port object 'MIIFPGA_TXD[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_TXD[1]}]
set_property PACKAGE_PIN AF24 [get_ports {MIIFPGA_TXD[2]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:267
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_TXD[2]' has been applied to the port object 'MIIFPGA_TXD[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_TXD[2]}]
set_property PACKAGE_PIN AF25 [get_ports {MIIFPGA_TXD[3]}]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:269
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_TXD[3]' has been applied to the port object 'MIIFPGA_TXD[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {MIIFPGA_TXD[3]}]
set_property PACKAGE_PIN AE22 [get_ports MIIFPGA_TXEN]
# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:271
# The conversion of 'IOSTANDARD' constraint on 'net' object 'MIIFPGA_TXEN' has been applied to the port object 'MIIFPGA_TXEN'.
set_property IOSTANDARD LVCMOS33 [get_ports MIIFPGA_TXEN]

# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:274
create_clock -period 40.000 -name MIIFPGA_RXC [get_ports MIIFPGA_RXC]

# The following cross clock domain false path constraints can be uncommented in order to mimic ucf constraints behavior (see message at the beginning of this file)
# set_false_path -from [get_clocks FPGA_CLK] -to [get_clocks [list AD9361_DATA_CLK_P AD9361_DATA_CLK_N MIIFPGA_RXC]]
# set_false_path -from [get_clocks AD9361_DATA_CLK_P] -to [get_clocks [list FPGA_CLK AD9361_DATA_CLK_N MIIFPGA_RXC]]
# set_false_path -from [get_clocks AD9361_DATA_CLK_N] -to [get_clocks [list FPGA_CLK AD9361_DATA_CLK_P MIIFPGA_RXC]]
# set_false_path -from [get_clocks MIIFPGA_RXC] -to [get_clocks [list FPGA_CLK AD9361_DATA_CLK_P AD9361_DATA_CLK_N]]

#NET "MIIFPGA_TXC" TNM_NET = "MII_TXC_Out";
#TIMESPEC TS_MII_TXC = PERIOD "MII_TXC_Out" 40 ns HIGH 50 %;

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets MIIFPGA_TXC]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets MIIFPGA_RXC]

# E:/work/MAN/vhdl/MAN_MT/MAN_MT_v4/src/sdc&ucf/JonetV15_UE_AD9361.ucf:286
set_input_delay -clock [get_clocks MIIFPGA_RXC] -max -add_delay 20.000 [get_ports {MIIFPGA_RXD[3] MIIFPGA_RXD[2] MIIFPGA_RXD[1] MIIFPGA_RXD[0] MIIFPGA_RXDV}]
# OFFSET specified with no VALID keyword, inferring one to yield a zero hold time
set_input_delay -clock [get_clocks MIIFPGA_RXC] -min -add_delay 0.000 [get_ports {MIIFPGA_RXD[3] MIIFPGA_RXD[2] MIIFPGA_RXD[1] MIIFPGA_RXD[0] MIIFPGA_RXDV}]
set_false_path -rise_from [get_clocks MIIFPGA_RXC] -through [get_ports {MIIFPGA_RXD[3] MIIFPGA_RXD[2] MIIFPGA_RXD[1] MIIFPGA_RXD[0] MIIFPGA_RXDV}] -fall_to [get_clocks MIIFPGA_RXC]

#TIMEGRP MII_TX =   PADS("MIIFPGA_TXEN" :
#        "MIIFPGA_TXD[0]" :
#        "MIIFPGA_TXD[1]" :
#        "MIIFPGA_TXD[2]" :
#        "MIIFPGA_TXD[3]");
#TIMEGRP "MII_TX" OFFSET = OUT 20 ns AFTER "MIIFPGA_TXC" LOW;



#NET "mo_MAN_MT_UserSlot_SP/mo_UserSlot_SP_TurboDec/mo_TurboDec/Trace_ins/BetaRam_ins/mem_adreg_0_I_19_0" KEEP = "TRUE";
#NET "mo_MAN_MT_UserSlot_SP/mo_UserSlot_SP_TurboDec/mo_TurboDec/Trace_ins/mem_N_1_0" KEEP = "TRUE";
#NET "mo_MAN_MT_UserSlot_SP/mo_UserSlot_SP_TurboDec/mo_TurboDec/Trace_ins/mem_N_1_2" KEEP = "TRUE";
#NET "mo_MAN_MT_UserSlot_SP/mo_UserSlot_SP_TurboDec/mo_TurboDec/Trace_ins/mem_N_1_1" KEEP = "TRUE";
#NET "VIO_SYNC_OUT[4]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT[5]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT[6]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT[7]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_0[4]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_1[4]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_0[6]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_1[6]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_0[7]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_1[7]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_2[7]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_0[5]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_1[5]" KEEP = "TRUE";
#NET "VIO_SYNC_OUT_2[5]" KEEP = "TRUE";

set_false_path -from [get_clocks AD9361_DATA_CLK_P] -to [get_clocks AD9361_DATA_CLK_N]
set_false_path -from [get_clocks AD9361_DATA_CLK_N] -to [get_clocks AD9361_DATA_CLK_P]




set_false_path -from [get_clocks -of_objects [get_pins mo_clkgen/mmcm_adv_inst/CLKOUT0]] -to [get_clocks AD9361_DATA_CLK_N]
set_false_path -from [get_clocks -of_objects [get_pins mo_clkgen/mmcm_adv_inst/CLKOUT0]] -to [get_clocks AD9361_DATA_CLK_P]
set_false_path -from [get_clocks AD9361_DATA_CLK_N] -to [get_clocks -of_objects [get_pins mo_clkgen/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks AD9361_DATA_CLK_P] -to [get_clocks -of_objects [get_pins mo_clkgen/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins mo_clkgen/mmcm_adv_inst/CLKOUT0]] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks -of_objects [get_pins mo_clkgen/mmcm_adv_inst/CLKOUT0]]
